In [1]:
using LightGraphs
using LightGraphsFlows

┌ Info: Precompiling LightGraphs [093fc24a-ae57-5d10-9952-331d41423f4d]
└ @ Base loading.jl:1186
┌ Info: Precompiling LightGraphsFlows [2f5eb75a-258c-59e0-affc-f41c55f75335]
└ @ Base loading.jl:1186


In [13]:
fg = DiGraph(6)

{6, 0} directed simple Int64 graph

In [14]:
E = [(6,1,16), (1,3,12), (3,5,20), (4,5,4), (2,4,14), (6,2,13), (1,2,18), (2,1,4), (3,2,9),
    (4,3,7)]

10-element Array{Tuple{Int64,Int64,Int64},1}:
 (6, 1, 16)
 (1, 3, 12)
 (3, 5, 20)
 (4, 5, 4) 
 (2, 4, 14)
 (6, 2, 13)
 (1, 2, 18)
 (2, 1, 4) 
 (3, 2, 9) 
 (4, 3, 7) 

In [15]:
capacity_matrix = zeros(Int, 6, 6)

6×6 Array{Int64,2}:
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0
 0  0  0  0  0  0

In [16]:
for e in E
    u, v, f = e
    add_edge!(fg, u, v)
    capacity_matrix[u,v] = f
end

In [17]:
f, F = maximum_flow(fg, 6, 5)

(2, [0 0 … 0 -1; 0 0 … 0 -1; … ; 0 0 … 0 0; 1 1 … 0 0])

In [18]:
f

2

In [19]:
F

6×6 Array{Int64,2}:
  0   0   1   0  0  -1
  0   0   0   1  0  -1
 -1   0   0   0  1   0
  0  -1   0   0  1   0
  0   0  -1  -1  0   0
  1   1   0   0  0   0