In [6]:
bitstr_len = 5;
num_init = 5;
init_pop = [rand(('0', '1'), bitstr_len) for i=1:num_init]

5-element Array{Array{Char,1},1}:
 ['0', '0', '1', '1', '0']
 ['0', '1', '1', '1', '0']
 ['1', '0', '1', '0', '0']
 ['0', '0', '1', '1', '1']
 ['0', '1', '0', '0', '1']

In [41]:
function getFitness(x)
    root = ""
    for val in x
        root *= string(val)
    end
    return parse(Int,root,base=2)
end

getFitness (generic function with 1 method)

In [44]:
getFitness(init_pop[1])

6

In [45]:
first_gen_fit = [getFitness(x) for x in init_pop]

5-element Array{Int64,1}:
  6
 14
 20
  7
  9

In [48]:
using Statistics

In [49]:
mean(first_gen_fit)

11.2

In [57]:
function select(pop, num)
    fits = [getFitness(x) for x in pop]
    return sample(pop, Weights(fits), num, replace=false)
end 

select (generic function with 1 method)

In [58]:
select(init_pop, 3)

3-element Array{Array{Char,1},1}:
 ['0', '1', '0', '0', '1']
 ['0', '0', '1', '1', '0']
 ['0', '0', '1', '1', '1']

In [50]:
function mutate(x, pct)
    idxs = [sample]

search: rand randn transcode macroexpand @macroexpand @macroexpand1



```
rand([rng=GLOBAL_RNG], [S], [dims...])
```

Pick a random element or array of random elements from the set of values specified by `S`; `S` can be

  * an indexable collection (for example `1:9` or `('x', "y", :z)`),
  * an `AbstractDict` or `AbstractSet` object,
  * a string (considered as a collection of characters), or
  * a type: the set of values to pick from is then equivalent to `typemin(S):typemax(S)` for integers (this is not applicable to [`BigInt`](@ref)), and to $[0, 1)$ for floating point numbers;

`S` defaults to [`Float64`](@ref).

!!! compat "Julia 1.1"
    Support for `S` as a tuple requires at least Julia 1.1.


# Examples

```julia-repl
julia> rand(Int, 2)
2-element Array{Int64,1}:
 1339893410598768192
 1575814717733606317

julia> rand(MersenneTwister(0), Dict(1=>2, 3=>4))
1=>2
```

!!! note
    The complexity of `rand(rng, s::Union{AbstractDict,AbstractSet})` is linear in the length of `s`, unless an optimized method with constant complexity is available, which is the case for `Dict`, `Set` and `BitSet`. For more than a few calls, use `rand(rng, collect(s))` instead, or either `rand(rng, Dict(s))` or `rand(rng, Set(s))` as appropriate.



In [54]:
using StatsBase

┌ Info: Precompiling StatsBase [2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91]
└ @ Base loading.jl:1186
